"""Emit project.godot for Godot 4.6, including an input map derived from the
project's control scheme + mechanics archetype. Pixel-art defaults (nearest filter,
integer-ish stretch) come from the target resolution."""
from __future__ import annotations

from pathlib import Path

# Godot 4 input event literals for the top-down / platformer action set.
_KEY = {
    # physical keycodes (Godot 4): W=87 A=65 S=83 D=68, arrows 4194319-22, space=32
    "move_up": [87, 4194320], "move_down": [83, 4194322],
    "move_left": [65, 4194319], "move_right": [68, 4194321],
    "jump": [32], "attack": [88],  # X
}


def input_map_for(archetype_kind: str) -> dict[str, list[int]]:
    if archetype_kind == "platformer_controller":
        return {k: _KEY[k] for k in ("move_left", "move_right", "jump", "attack")}
    if archetype_kind == "turn_based_combat":
        return {k: _KEY[k] for k in ("move_up", "move_down", "move_left", "move_right", "attack")}
    # top_down_controller (default)
    return {k: _KEY[k] for k in ("move_up", "move_down", "move_left", "move_right", "attack")}


def _input_event(keycode: int) -> str:
    return (f'Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"",'
            f'"device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,'
            f'"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,'
            f'"physical_keycode":{keycode},"key_label":0,"unicode":0,"location":0,'
            f'"echo":false,"script":null)')


def _input_section(input_map: dict[str, list[int]]) -> str:
    lines = ["[input]", ""]
    for action, keys in input_map.items():
        events = ",".join(_input_event(k) for k in keys)
        lines.append(f'{action}={{')
        lines.append('"deadzone": 0.5,')
        lines.append(f'"events": [{events}]')
        lines.append('}')
    return "\n".join(lines)


def write_project_godot(project_dir: str | Path, *, name: str, main_scene: str,
                        width: int, height: int, archetype_kind: str) -> Path:
    project_dir = Path(project_dir)
    project_dir.mkdir(parents=True, exist_ok=True)
    body = f'''; Engine configuration — generated by meristem-compiler. Deterministic projection
; of the manifest. Hand-edits outside generated regions are preserved on recompile.
config_version=5

[application]

config/name="{name}"
run/main_scene="{main_scene}"
config/features=PackedStringArray("4.6", "GL Compatibility")

[display]

window/size/viewport_width={width}
window/size/viewport_height={height}
window/stretch/mode="viewport"
window/stretch/aspect="keep"

{_input_section(input_map_for(archetype_kind))}

[rendering]

renderer/rendering_method="gl_compatibility"
textures/canvas_textures/default_texture_filter=0
'''
    path = project_dir / "project.godot"
    path.write_text(body, encoding="utf-8")
    return path
